### ISSUE TITLE
Congratulations...

### ISSUE THREAD

**Issue by henriquehrf** [glaysons/SeleniumParser#1]
Parabéns pela iniciativa do projeto. @glaysons 

Baixei o projeto e vi que já tem bastante coisa desenvolvida. Já faz um tempinho que não estou atuando diretamente com o Selenium, porém já estou lendo a respeito para relembrar todos recursos desse framework.

Se possível, poderia conceder permissão para contribuir com o repositório? Outra coisa, já tem um escopo do que terá numa versão stable deste projeto? Poderiamos organizar essas ideias no Projects do github.

Outra coisa... No projeto Sample, ao baixar e realizar a build, o VS exibe um erro de compilação por não localizar as referências:
`Import Project="packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\...`

A correção que eu fiz aqui foi ajustar a localização da pasta:

`Import Project="..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.2.0.1\...`

**Comment by glaysons** [comment]
Olá jovem, muito obrigado ...

Acesso concedido, seja bem vindo. Farei a correção e te aviso.

Abraços.
